#!/bin/bash

if [[ ! "$1" ]]; then

    TMP=/tmp/scan1.png

    echo Use mouse select an area on screen to decode QR
    echo ""

    spectacle -b -r -n -o $TMP
    OUTPUT=$(echo $(zbarimg -q $TMP) | sed 's/^.*Code://')
    xdg-open $OUTPUT
    echo $OUTPUT

else
    qrencode -m 2 -t ANSIUTF8 "$1"
fi
