#!/bin/bash

if [[ ! "$1" ]]; then

    INPUT=/tmp/scan-input.png
    PROCESSED=/tmp/scan-output.png

    echo Use mouse select an area on screen, then press enter, to decode QR.
    echo ""

    spectacle -b -r -n -o $INPUT
    convert $INPUT +dither  -colors 2  -colorspace gray -normalize $PROCESSED
    OUTPUT=$(echo $(zbarimg -q $PROCESSED) | sed 's/^.*Code://')
    echo $OUTPUT
    if [[ "$OUTPUT" == "https"* || "$OUTPUT" == "http"* ]]; then
        echo "Opening Link..."
        xdg-open $OUTPUT
    fi

else
    qrencode -m 2 -t ANSIUTF8 "$1"
fi
